# Generated by Django 3.1.4 on 2020-12-25 07:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='room',
            managers=[
                ('activeRooms', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
