# Generated by Django 3.1.4 on 2020-12-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0002_auto_20201225_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='masterPassword',
            field=models.CharField(default=models.CharField(max_length=256), max_length=256),
        ),
    ]
