# Generated by Django 3.1.4 on 2020-12-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0003_room_masterpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='budget',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
